import { PERMISSION, ROLE } from "../enum";

export const permissions = {
  [ROLE.ADMIN]: [
    PERMISSION.USER_GET,
    PERMISSION.USER_POST,
    PERMISSION.USER_DELETE,
    PERMISSION.USER_PUT,
    PERMISSION.TODO_PUT,
    PERMISSION.TODO_POST,
    PERMISSION.TODO_DELETE,
    PERMISSION.TODO_GET,
  ],
  [ROLE.USER]: [
    PERMISSION.TODO_PUT,
    PERMISSION.TODO_POST,
    PERMISSION.TODO_DELETE,
    PERMISSION.TODO_GET,
  ],
};
