name: CI/CD Pipeline

on:
  push:
    branches:
      - assignment-2
  pull_request:
    branches:
      - assignment-2
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shresritik
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: shresritik/todo:v2.0.0
